### PR TITLE
fix the bugs of random commands

### LINKED ISSUE #145: [PE-D] Number of Unreviewed Flashcards Does Not Tally
In some cases where the flashcards in the list are both unreviewed, doing the random function (Yes and No for reviewed) - shows that there is -1 flashcard still unreviewed.

None of the flashcards were marked as reviewed during random but the number of flashcards still unreviewed becomes 1 (instead of 2).

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: nigellenl/ped#5

### LINKED ISSUE #157: [PE-D] Random command review
During the review of cards upon entering the ```random``` command, when the app asks the user if it should mark the card as reviewed, any answer input by the user that is not "yes" (e.g. if i put "hi" instead, or if i make an unfortunate and unintentional typo mistake) will be marked as "no" instead of throwing an exception/asking the user to input an answer in the correct format.

It also does not accept "Y" or "y", which are the more common ways of indication yes or no.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: JeremiasLiew/ped#9

### PR DESCRIPTION
**Pull request by sliu107**

### CODE REVIEW

File: src/main/java/seedu/tp/flashcard/FlashcardList.java [hunk 1]
```diff
@@ -146,22 +151,45 @@ public FlashcardList reviewRandomFlashcards(Ui ui) throws InvalidFlashcardIndexE
...
+                    break;
+                case "n":
+                case "no":
+                    break;
+                default:
+                    throw new InvalidInputFormatException();
+                }
+                return reviewedNumber;
+            } catch (InvalidInputFormatException e) {
+                System.out.println("The answer given is not acceptable. Please enter again.");
```
Comment (g-lilian) [inline src/main/java/seedu/tp/flashcard/FlashcardList.java]: I think a clearer way to phrase it can simply be "Please enter either yes/no."

**Review by g-lilian — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/tp/flashcard/FlashcardList.java (hunk 1 above)
Comment (Zhilin-Huang) [reply src/main/java/seedu/tp/flashcard/FlashcardList.java]: > I think a clearer way to phrase it can simply be "Please enter either yes/no."

Agree!
